CREATE TABLE district
(
  dist_slno bigserial NOT NULL,
  dist_state integer,
  dist_id integer,
  dist_name character varying NOT NULL,
  status integer,
    user_created_on timestamp with time zone DEFAULT now(),
  CONSTRAINT district_pkey PRIMARY KEY (dist_id)
);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Adilabad',1);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Agra',2);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Ahmed Nagar',3);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Ahmedabad City',4);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (24,'Aizawl',5);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Ajmer',6);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Akola',7);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Aligarh',8);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Allahabad',9);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Alleppey',10);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Almora',11);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Alwar',12);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Alwaye',13);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Amalapuram',14);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (13,'Ambala',15);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Ambedkar Nagar',16);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Amravati',17);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Amreli',18);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Amritsar',19);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Anakapalle',20);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Anand',21);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Anantapur',22);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Ananthnag',23);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Anna Road H.O',24);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Arakkonam',25);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Asansol',26);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Aska',27);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Auraiya',28);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Aurangabad',29);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Aurangabad(Bihar)',30);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Azamgarh',31);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Bagalkot',32);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Bageshwar',33);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Bagpat',34);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Bahraich',35);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Balaghat',36);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Balangir',37);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Balasore',38);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Ballia',39);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Balrampur',40);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Banasanktha',41);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Banda',42);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Bandipur',43);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Bankura',44);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Banswara',45);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Barabanki',46);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Baramulla',47);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Baran',48);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Bardoli',49);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Bareilly',50);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Barmer',51);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Barnala',52);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Barpeta',53);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (7,'Bastar',54);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Basti',55);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Bathinda',56);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Beed',57);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Begusarai',58);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Belgaum',59);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Bellary',60);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Bengaluru East',61);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Bengaluru South',62);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Bengaluru West',63);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Berhampur',64);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Bhadrak',65);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Bhagalpur',66);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Bhandara',67);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Bharatpur',68);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Bharuch',69);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Bhavnagar',70);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Bhilwara',71);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Bhimavaram',72);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (13,'Bhiwani',73);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Bhojpur',74);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Bhopal',75);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Bhubaneswar',76);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Bidar',77);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Bijapur',78);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Bijnor',79);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Bikaner',80);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (7,'Bilaspur',81);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Birbhum',82);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (22,'Bishnupur',83);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Bongaigaon',84);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Budaun',85);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Budgam',86);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Bulandshahr',87);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Buldhana',88);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Bundi',89);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Burdwan',90);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Cachar',91);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Calicut',92);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (1,'Carnicobar',93);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (14,'Chamba',94);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Chamoli',95);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Champawat',96);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (24,'Champhai',97);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Chandauli',98);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (22,'Chandel',99);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (6,'Chandigarh',100);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Chandrapur',101);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Changanacherry',102);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Changlang',103);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Channapatna',104);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Chengalpattu',105);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Chennai City Central',106);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Chennai City North',107);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Chennai City South',108);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Chhatarpur',109);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Chhindwara',110);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Chikmagalur',111);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Chikodi',112);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Chitradurga',113);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Chitrakoot',114);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Chittoor',115);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Chittorgarh',116);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (22,'Churachandpur',117);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Churu',118);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Coimbatore',119);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Contai',120);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Cooch Behar',121);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Cuddalore',122);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Cuddapah',123);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Cuttack City',124);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Cuttack North',125);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Cuttack South',126);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (8,'Dadra & Nagar Haveli',127);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (9,'Daman',128);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Darbhanga',129);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Darjiling',130);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Darrang',131);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Dausa',132);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (14,'Dehra Gopipur',133);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Dehradun',134);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (10,'Delhi',135);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Deoria',136);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (33,'Dhalai',137);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (16,'Dhanbad',138);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (14,'Dharamsala',139);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Dharmapuri',140);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Dharwad',141);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Dhemaji',142);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Dhenkanal',143);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Dholpur',144);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Dhubri',145);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Dhule',146);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Dibang Valley',147);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Dibrugarh',148);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (1,'Diglipur',149);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Dimapur',150);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Dindigul',151);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (9,'Diu',152);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Doda',153);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Dungarpur',154);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (7,'Durg',155);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'East Champaran',156);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (23,'East Garo Hills',157);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'East Kameng',158);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (23,'East Khasi Hills',159);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'East Siang',160);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (30,'East Sikkim',161);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Eluru',162);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Ernakulam',163);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Erode',164);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Etah',165);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Etawah',166);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Faizabad',167);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (13,'Faridabad',168);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Faridkot',169);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Farrukhabad',170);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Fatehgarh Sahib',171);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Fatehpur',172);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Fazilka',173);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (1,'Ferrargunj',174);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Firozabad',175);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Firozpur',176);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Gadag',177);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Gadchiroli',178);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Gandhinagar',179);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Ganganagar',180);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Gautam Buddha Nagar',181);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Gaya',182);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Ghaziabad',183);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Ghazipur',184);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (16,'Giridih',185);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (11,'Goa',186);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Goalpara',187);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Gokak',188);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Golaghat',189);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Gonda',190);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Gondal',191);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Gondia',192);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Gorakhpur',193);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Gudivada',194);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Gudur',195);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Gulbarga',196);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Guna',197);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Guntur',198);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Gurdaspur',199);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (13,'Gurugram',200);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Gwalior',201);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Hailakandi',202);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (14,'Hamirpur (HP)',203);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Hamirpur (UP)',204);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Hanamkonda',205);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Hanumangarh',206);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Hardoi',207);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Haridwar',208);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Hassan',209);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Hathras',210);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Haveri',211);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (16,'Hazaribagh',212);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Hindupur',213);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Hingoli',214);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (13,'Hissar',215);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Hooghly',216);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Hoshangabad',217);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Hoshiarpur',218);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Howrah',219);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (1,'Hut Bay',220);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Hyderabad City',221);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Hyderabad South East',222);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Idukki',223);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (22,'Imphal East',224);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (22,'Imphal West',225);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Indore City',226);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Indore Moffusil',227);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Irinjalakuda',228);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Jabalpur',229);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (23,'Jaintia Hills',230);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Jaipur',231);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Jaisalmer',232);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Jalandhar',233);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Jalaun',234);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Jalgaon',235);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Jalna',236);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Jalor',237);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Jalpaiguri',238);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Jammu',239);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Jamnagar',240);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Jaunpur',241);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Jhalawar',242);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Jhansi',243);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Jhujhunu',244);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Jodhpur',245);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Jorhat',246);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Junagadh',247);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Jyotiba Phule Nagar',248);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Kakinada',249);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Kalahandi',250);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Kamrup',251);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Kanchipuram',252);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Kannauj',253);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Kanniyakumari',254);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Kannur',255);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Kanpur Dehat',256);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Kanpur Nagar',257);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Kapurthala',258);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (27,'Karaikal',259);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Karaikudi',260);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Karauli',261);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Karbi Anglong',262);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Kargil',263);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Karimganj',264);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Karimnagar',265);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (13,'Karnal',266);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Karur',267);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Karwar',268);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Kasaragod',269);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Kathua',270);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Kaushambi',271);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Keonjhar',272);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Khammam (AP)',273);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Khammam (TL)',274);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Khandwa',275);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Kheda',276);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Kheri',277);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Kiphire',278);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Kodagu',279);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Kohima',280);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Kokrajhar',281);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Kolar',282);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (24,'Kolasib',283);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Kolhapur',284);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Kolkata',285);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Koraput',286);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Kota',287);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Kottayam',288);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Kovilpatti',289);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Krishnagiri',290);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Kulgam',291);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Kumbakonam',292);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Kupwara',293);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Kurnool',294);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (13,'Kurukshetra',295);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Kurung Kumey',296);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Kushinagar',297);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Kutch',298);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Lakhimpur',299);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (19,'Lakshadweep',300);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Lalitpur',301);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Latur',302);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (24,'Lawngtlai',303);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Leh',304);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Lohit',305);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Longleng',306);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Lower Subansiri',307);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Lucknow',308);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Ludhiana',309);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (24,'Lunglei',310);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Machilipatnam',311);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Madhubani',312);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Madurai',313);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Mahabubnagar',314);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Maharajganj',315);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Mahesana',316);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Mahoba',317);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Mainpuri',318);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Malda',319);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (24,'Mammit',320);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (14,'Mandi',321);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Mandsaur',322);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Mandya',323);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Mangalore',324);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Manjeri',325);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Mansa',326);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Marigaon',327);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Mathura',328);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Mau',329);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Mavelikara',330);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (1,'Mayabander',331);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Mayiladuthurai',332);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Mayurbhanj',333);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Medak',334);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Meerut',335);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (23,'Meghalaya',336);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Midnapore',337);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Mirzapur',338);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Moga',339);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Mohali',340);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Mokokchung',341);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Mon',342);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Monghyr',343);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Moradabad',344);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Morena',345);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Muktsar',346);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Mumbai',347);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Murshidabad',348);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Muzaffarnagar',349);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Muzaffarpur',350);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Mysore',351);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Nadia',352);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Nagaon',353);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Nagapattinam',354);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Nagaur',355);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Nagpur',356);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Nainital',357);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Nalanda',358);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Nalbari',359);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Nalgonda',360);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Namakkal',361);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (1,'Nancorie',362);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (1,'Nancowrie',363);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Nanded',364);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Nandurbar',365);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Nandyal',366);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Nanjangud',367);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Narasaraopet',368);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Nashik',369);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Navsari',370);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Nawadha',371);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Nawanshahr',372);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Nellore',373);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Nilgiris',374);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Nizamabad',375);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'North 24 Parganas',376);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'North Cachar Hills',377);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'North Dinajpur',378);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (30,'North Sikkim',379);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (33,'North Tripura',380);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Osmanabad',381);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Ottapalam',382);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (16,'Palamau',383);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Palghat',384);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Pali',385);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Panchmahals',386);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Papum Pare',387);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Parbhani',388);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Parvathipuram',389);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Patan',390);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Pathanamthitta',391);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Patiala',392);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Patna',393);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Pattukottai',394);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Pauri Garhwal',395);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Peddapalli',396);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Peren',397);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Phek',398);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Phulbani',399);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Pilibhit',400);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Pithoragarh',401);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (27,'Poducherry (PD)',402);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Poducherry (TN)',403);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Pollachi',404);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Poonch',405);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Porbandar',406);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (1,'Port Blair',407);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Prakasam',408);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Pratapgarh',409);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Proddatur',410);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Pudukkottai',411);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Pulwama',412);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Pune',413);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Puri',414);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Purnea',415);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Purulia',416);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Puttur',417);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Quilon',418);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Raebareli',419);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Raichur',420);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (7,'Raigarh (CT)',421);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Raigarh (MH)',422);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (7,'Raipur',423);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Rajahmundry',424);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Rajauri',425);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Rajkot',426);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Rajsamand',427);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Ramanathapuram',428);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Rampur',429);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (14,'Rampur Bushahr',430);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (16,'Ranchi',431);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (1,'Rangat',432);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Ratlam',433);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Ratnagiri',434);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Reasi',435);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Rewa',436);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (23,'Ri Bhoi',437);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (13,'Rohtak',438);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Rohtas',439);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Ropar',440);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Rudraprayag',441);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Rupnagar',442);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Sabarkantha',443);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Sagar',444);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Saharanpur',445);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Saharsa',446);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Salem East',447);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Salem West',448);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Samastipur',449);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Sambalpur',450);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Sangareddy',451);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Sangli',452);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Sangrur',453);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Sant Kabir Nagar',454);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Sant Ravidas Nagar',455);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (16,'Santhal Parganas',456);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Saran',457);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Satara',458);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Sawai Madhopur',459);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Secunderabad',460);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Sehore',461);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (22,'Senapati',462);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (24,'Serchhip',463);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Shahdol',464);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Shahjahanpur',465);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (14,'Shimla',466);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Shimoga',467);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Shrawasti',468);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Sibsagar',469);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Siddharthnagar',470);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Sikar',471);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Sindhudurg',472);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (16,'Singhbhum',473);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Sirohi',474);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Sirsi',475);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Sitamarhi',476);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Sitapur',477);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Sivaganga',478);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Siwan',479);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (14,'Solan',480);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Solapur',481);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Sonbhadra',482);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (13,'Sonepat',483);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Sonitpur',484);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'South 24 Parganas',485);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'South Dinajpur',486);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (23,'South Garo Hills',487);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (30,'South Sikkim',488);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (33,'South Tripura',489);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Srikakulam',490);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Srinagar',491);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Srirangam',492);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Sultanpur',493);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (26,'Sundargarh',494);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Surat',495);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Surendranagar',496);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Suryapet',497);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Tadepalligudem',498);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Tambaram',499);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (22,'Tamenglong',500);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (36,'Tamluk',501);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (28,'Tarn Taran',502);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Tawang',503);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Tehri Garhwal',504);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Tenali',505);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Thalassery',506);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Thane',507);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Thanjavur',508);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Theni',509);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (22,'Thoubal',510);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (4,'Tinsukia',511);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Tirap',512);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Tiruchirapalli',513);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Tirunelveli',514);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Tirupati',515);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Tirupattur',516);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Tirupur',517);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Tirur',518);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Tiruvalla',519);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Tiruvannamalai',520);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Tonk',521);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Trichur',522);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Trivandrum North',523);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Trivandrum South',524);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Tuensang',525);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Tumkur',526);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Tuticorin',527);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (29,'Udaipur',528);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Udham Singh Nagar',529);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (15,'Udhampur',530);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (17,'Udupi',531);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Ujjain',532);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (22,'Ukhrul',533);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (14,'Una',534);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Unnao',535);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Upper Siang',536);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'Upper Subansiri',537);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (35,'Uttarkashi',538);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (18,'Vadakara',539);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Vadodara East',540);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Vadodara West',541);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'Vaishali',542);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (12,'Valsad',543);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (34,'Varanasi',544);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Vellore',545);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (20,'Vidisha',546);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Vijayawada',547);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Virudhunagar',548);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Visakhapatnam',549);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (2,'Vizianagaram',550);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (31,'Vriddhachalam',551);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Wanaparthy',552);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (32,'Warangal',553);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Wardha',554);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Washim',555);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (5,'West Champaran',556);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (23,'West Garo Hills',557);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'West Kameng',558);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (23,'West Khasi Hills',559);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (3,'West Siang',560);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (30,'West Sikkim',561);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (33,'West Tripura',562);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Wokha',563);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (21,'Yavatmal',564);
INSERT INTO district(dist_state,dist_name,dist_id) VALUES (25,'Zunhebotto',565);